### ISSUE TITLE
Grpc version ?

### ISSUE THREAD

**Issue by abishekh** [CogRob/catkin_grpc#19]
Does this pull in the latest stable version of GRPC ?

**Comment by BillWSY** [comment]
The short answer is no. We pin to some versions we know would work and sync with the head periodically. As of today, it is grpc 1.6.3 (https://github.com/grpc/grpc/releases/tag/v1.6.3).

The git commit (sha1 hash) of grpc repo is specified in the CMakeLists, for example https://github.com/CogRob/catkin_grpc/blob/0b9fa594775dc1ea95686db0e6536027922a1f8c/grpc/CMakeLists.txt#L7 We manually sync these sha1 hash periodically (including those in third_party directory) and make sure it still builds with catkin in the ROS build farm before a release.

You are more than welcome to sync these sha1 hashes with the latest and PR.

**Comment by BillWSY** [comment]
FYI, manually specifying these sha1 tags was introduced in https://github.com/CogRob/catkin_grpc/pull/11/commits/6ebdbfd407cf2277cab26fd97ffd2b05c0c8c0c3. Before that, we pin to tag 1.6.x, which is always the latest 1.6.x release.

There were two reasons:
* We wanted to notify ROS build farm and rebuild the package when grpc has a new release.
* ROS build farm fails on ARM architecture if we use git to download because it takes forever (>720 minutes) to `git clone` in qemu, mainly because of the huge history tree of grpc and third_party repos.

**Comment by abishekh** [comment]
Thanks :)
